### ISSUE TITLE
Registering Empty todo

### ISSUE THREAD

**Issue by vakhariaheet** [abhinavg916/do-more#1]
Can I fix that?

**Comment by abhinavg916** [comment]
Good observation. I forget to take care of that.
Go ahead try! 👍

**Comment by vakhariaheet** [comment]
Thank you😇

**Comment by vakhariaheet** [comment]
Hey Bro, can you plz add the Hacktoberfect tag in the repo so that my pr will be accepted in Hacktoberfest

**Comment by abhinavg916** [comment]
Ok. 
Do you really need that T-Shirt? ;)

**Comment by vakhariaheet** [comment]
Yes

**Comment by abhinavg916** [comment]
I have the added tag in topics for hacktoberfest. Is it visible to you?

**Comment by vakhariaheet** [comment]
Yes
